CHINESE_PACK = {"tips": "提示",
                "connectSuccess": "创建连接成功！",
                "connectFail": "创建连接失败！",
                "success": "成功！",
                "fail": "失败!",
                "forwardPower": "前项功:",
                "backwardPower": "后项功:",
                "returnLoss": "损耗:",
                "standingWaveRatio": "驻波比:",
                "restoreFactory":"是否要将设备恢复出厂设置?",
                "noConnect":"请先连接读写器！",
                "deviceName":"读写器名称:",
                "softVersion":"软件版本:",
                "openTime":"上电后过去了:",
                "basebandVersion":"基带版本:",
                "deviceSN":"设备SN:",
                "deivceTemperature":"读写器温度:"
                }