ENGLISH_PACK = {"tips": "tips",
                "connectSuccess": "connect success！",
                "connectFail": "connect fail！",
                "success": "success！",
                "fail": "fail!",
                "forwardPower": "forwardPower:",
                "backwardPower": "backwardPower:",
                "returnLoss": "returnLoss:",
                "standingWaveRatio": "standingWaveRatio:",
                "restoreFactory":"Do you want to restore the device to factory settings?",
                "noConnect":"Please connect the reader writer first",
                "deviceName":"deviceName:",
                "softVersion":"softVersion:",
                "openTime":"openTime:",
                "basebandVersion":"basebandVersion:",
                "deviceSN":"deviceSN:",
                "deivceTemperature":"deivceTemperature:"
                }