# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'usbConnect.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(372, 174)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 50, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_ok = QtWidgets.QPushButton(Form)
        self.btn_ok.setGeometry(QtCore.QRect(170, 130, 75, 23))
        self.btn_ok.setObjectName("btn_ok")
        self.btn_canel = QtWidgets.QPushButton(Form)
        self.btn_canel.setGeometry(QtCore.QRect(260, 130, 75, 23))
        self.btn_canel.setObjectName("btn_canel")
        self.cb_connectParam = QtWidgets.QComboBox(Form)
        self.cb_connectParam.setGeometry(QtCore.QRect(80, 80, 211, 22))
        self.cb_connectParam.setObjectName("cb_connectParam")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "USB Connect"))
        self.label.setText(_translate("Form", "连接参数："))
        self.btn_ok.setText(_translate("Form", "确定"))
        self.btn_canel.setText(_translate("Form", "取消"))
